input-files:
  - cover.md
  - xiao_coin_ebook.md
output-file: xiao_coin_ebook.pdf
pdf-engine: xelatex
variables:
  CJKmainfont: "Noto Sans CJK JP"
  mainfont: "Noto Sans CJK JP"
  geometry: "margin=2cm"
  documentclass: "article"
  fontsize: "11pt"
  linestretch: "1.2"
  toc: true
  toc-depth: 3
  number-sections: true
  colorlinks: true
  linkcolor: "blue"
  urlcolor: "blue"
  citecolor: "blue" 